use anyhow::{Context, Result};
use clap::{Arg, ArgMatches, Command};
use otunnel::config::Span;

pub fn command() -> Command {
    Command::new("cloudflared")
        .about("Inspect the Cloudflare Tunnel companion")
        .arg_required_else_help(true)
        .subcommand(
            Command::new("config")
                .about("Print a standalone cloudflared configuration")
                .arg(Arg::new("token-file").long("token-file").default_value(""))
                .args(
                    [
                        ("metrics-address", "127.0.0.1:20241"),
                        ("log-level", "info"),
                        ("transport-log-level", "warn"),
                        ("protocol", "auto"),
                        ("edge-ip-version", "auto"),
                        ("retries", "5"),
                        ("grace-period", "30s"),
                    ]
                    .map(|(name, default)| {
                        Arg::new(name)
                            .long(name)
                            .default_value(default)
                            .allow_hyphen_values(true)
                    }),
                ),
        )
}

pub fn execute(arguments: &ArgMatches) -> Result<u8> {
    let (_, arguments) = arguments
        .subcommand()
        .context("missing cloudflared command")?;
    let value = |name| {
        arguments
            .get_one::<String>(name)
            .map(String::as_str)
            .unwrap_or_default()
            .trim()
    };
    let token = value("token-file");
    anyhow::ensure!(
        !token.is_empty(),
        "cloudflared config: --token-file is required"
    );
    for name in [
        "token-file",
        "metrics-address",
        "log-level",
        "transport-log-level",
        "protocol",
        "edge-ip-version",
    ] {
        let value = value(name);
        anyhow::ensure!(
            !value.is_empty(),
            "cloudflared config: --{name} must not be empty"
        );
        anyhow::ensure!(
            !value.contains(['\0', '\r', '\n']),
            "cloudflared config: --{name} must be a single line"
        );
    }
    let metrics = value("metrics-address");
    let (host, port) = metrics
        .rsplit_once(':')
        .context("cloudflared config: invalid --metrics-address: missing port in address")?;
    anyhow::ensure!(
        !host.trim().is_empty(),
        "cloudflared config: --metrics-address must include a host"
    );
    anyhow::ensure!(
        !host.contains(':') || host.starts_with('[') && host.ends_with(']'),
        "cloudflared config: invalid --metrics-address: too many colons in address"
    );
    anyhow::ensure!(
        port.parse::<u16>().is_ok_and(|port| port != 0),
        "cloudflared config: --metrics-address port must be between 1 and 65535"
    );
    for (name, allowed) in [
        (
            "log-level",
            &["debug", "info", "warn", "error", "fatal"][..],
        ),
        (
            "transport-log-level",
            &["debug", "info", "warn", "error", "fatal"][..],
        ),
        ("protocol", &["auto", "http2", "quic"][..]),
        ("edge-ip-version", &["auto", "4", "6"][..]),
    ] {
        let value = value(name);
        anyhow::ensure!(
            allowed.contains(&value),
            "cloudflared config: invalid --{name} {value:?}; expected one of {}",
            allowed.join(", ")
        );
    }
    let retries: i64 = value("retries").parse().context("invalid --retries")?;
    anyhow::ensure!(
        retries >= 0,
        "cloudflared config: --retries must be non-negative"
    );
    let grace: Span = serde_json::from_value(serde_json::json!(value("grace-period")))?;
    anyhow::ensure!(
        !grace.0.is_zero(),
        "cloudflared config: --grace-period must be positive"
    );
    let quoted = |value: &str| serde_json::to_string(value);
    let mut output = String::from(
        "# Generated by tunnel-client cloudflared config.\n# Token-free by design: the file references a token path but never embeds the token.\n# Run directly with: TUNNEL_MANAGEMENT_DIAGNOSTICS=false cloudflared tunnel --config /etc/cloudflared/config.yml run\n",
    );
    output.push_str(&format!(
        "token-file: {}\nno-autoupdate: true\n",
        quoted(token)?
    ));
    for (field, name) in [
        ("metrics", "metrics-address"),
        ("loglevel", "log-level"),
        ("transport-loglevel", "transport-log-level"),
        ("protocol", "protocol"),
        ("edge-ip-version", "edge-ip-version"),
    ] {
        output.push_str(&format!("{field}: {}\n", quoted(value(name))?));
    }
    output.push_str(&format!(
        "retries: {retries}\ngrace-period: {}\n",
        quoted(&grace.to_string())?
    ));
    print!("{output}");
    Ok(0)
}
